
package com.pw2webservice.pw2xmlwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XmlService", targetNamespace = "http://pw2xmlwebservice.pw2webservice.com/", wsdlLocation = "http://localhost:9080/XmlService?wsdl")
public class XmlService_Service
    extends Service
{

    private final static URL XMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException XMLSERVICE_EXCEPTION;
    private final static QName XMLSERVICE_QNAME = new QName("http://pw2xmlwebservice.pw2webservice.com/", "XmlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/XmlService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLSERVICE_WSDL_LOCATION = url;
        XMLSERVICE_EXCEPTION = e;
    }

    public XmlService_Service() {
        super(__getWsdlLocation(), XMLSERVICE_QNAME);
    }

    public XmlService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLSERVICE_QNAME, features);
    }

    public XmlService_Service(URL wsdlLocation) {
        super(wsdlLocation, XMLSERVICE_QNAME);
    }

    public XmlService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLSERVICE_QNAME, features);
    }

    public XmlService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XmlService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XmlService
     */
    @WebEndpoint(name = "XmlServicePort")
    public XmlService getXmlServicePort() {
        return super.getPort(new QName("http://pw2xmlwebservice.pw2webservice.com/", "XmlServicePort"), XmlService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XmlService
     */
    @WebEndpoint(name = "XmlServicePort")
    public XmlService getXmlServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pw2xmlwebservice.pw2webservice.com/", "XmlServicePort"), XmlService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLSERVICE_EXCEPTION!= null) {
            throw XMLSERVICE_EXCEPTION;
        }
        return XMLSERVICE_WSDL_LOCATION;
    }

}
