
package com.pw2webservice.pw2xmlwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Big", targetNamespace = "http://ws.ifrs.edu/", wsdlLocation = "http://localhost:9080/Big?wsdl")
public class Big_Service
    extends Service
{

    private final static URL BIG_WSDL_LOCATION;
    private final static WebServiceException BIG_EXCEPTION;
    private final static QName BIG_QNAME = new QName("http://ws.ifrs.edu/", "Big");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/Big?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIG_WSDL_LOCATION = url;
        BIG_EXCEPTION = e;
    }

    public Big_Service() {
        super(__getWsdlLocation(), BIG_QNAME);
    }

    public Big_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIG_QNAME, features);
    }

    public Big_Service(URL wsdlLocation) {
        super(wsdlLocation, BIG_QNAME);
    }

    public Big_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIG_QNAME, features);
    }

    public Big_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Big_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Big
     */
    @WebEndpoint(name = "BigPort")
    public Big getBigPort() {
        return super.getPort(new QName("http://ws.ifrs.edu/", "BigPort"), Big.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Big
     */
    @WebEndpoint(name = "BigPort")
    public Big getBigPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ifrs.edu/", "BigPort"), Big.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIG_EXCEPTION!= null) {
            throw BIG_EXCEPTION;
        }
        return BIG_WSDL_LOCATION;
    }

}
